jdgram/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, :controllers => { registrations: 'registrations' }  
  resources :posts, :users
  
  resources :posts do
    resources :comments
  end



end

jdgram/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

jdgram/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

jdgram/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy 
  belongs_to :user
  validates :image, presence: true
  validates :user_id, presence: true 
  has_attached_file :image, styles: { :medium => "340x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

jdgram/app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

jdgram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in


end

jdgram/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id 

    if @comment.save
      redirect_to :back
    else
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    @comment.destroy

    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

jdgram/app/controllers/posts_controller.rb
class PostsController < ApplicationController  
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :post_owner, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
    @posts = @posts.sort_by {|post| post.created_at}.reverse
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_owner 
  unless current_user == @post.user
    flash[:alert] = "That post doesn't belong to you!"
    redirect_to root_path
  end
end  
end  

jdgram/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
  
end  

jdgram/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate
      session[:user_id] = user.id
      redirect_to user_path
    else
      redirect '/'
    end
  end

  def edit
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

jdgram/app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

jdgram/app/helpers/comments_helper.rb
module CommentsHelper
end

jdgram/app/helpers/posts_helper.rb
module PostsHelper
end

jdgram/app/helpers/sessions_helper.rb
module SessionsHelper
end

jdgram/app/helpers/users_helper.rb
module UsersHelper
end

jdgram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jdgram</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="nav">
      <nav>
        <ul id="home">
          <li><%= link_to "JdGRAM", root_path%></li>
        </ul>
        <ul id="links">
          <% if user_signed_in?%>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

jdgram/app/views/posts/edit.html.erb
<%= image_tag @post.image.url(:medium) %>

<%= form_for(@post) do |f| %>
  <%=f.file_field :image %>
  <%= f.text_field :caption %>
  <%= f.submit "Edit image" %>
<% end %>

jdgram/app/views/posts/index.html.erb
<header id="photogram">
  <h1>JdGram</h1>
</header>

<% @posts.each do |post| %>
<div class="gram-post card-panel center card">
  <div class="username-wrapper">
    <div class="username">
      <h6 class="username-link"><%= link_to post.user.user_name, user_path(post.user) %> </h6>
      <p class="timestamp">Posted: <%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
  </div>
  <div class="gram-image">
  <%= link_to image_tag(post.image.url(:medium)), post_path(post) %>
  </div>
  <div class="post-caption">
  <p><%= post.caption %></p>
  </div>  
</div>
<% end %>

jdgram/app/views/posts/new.html.erb
<div class="new-post card-panel">
<%= form_for(@post) do |f| %>
  File: <%=f.file_field :image %>
  <br>
  <%= f.text_field :caption, placeholder: "Add a caption" %>
  <%= f.submit "Add image" %>
<% end %>
</div>

jdgram/app/views/posts/show.html.erb
<div class="gram-post card-panel center">
<%= @post.user.user_name %><br>
<%= image_tag @post.image.url(:medium) %><br>
<%= @post.caption %>

<% @post.comments.each do |comment| %>
  <div class="comment">
    <p><%= comment.content %></p>
    <% if comment.user == current_user %>
      <%= link_to post_comment_path(post, comment), method: :delete %>
    <% end %>
  </div>
<% end %>


<% if @post.user.id == current_user.id %>
<p><%= link_to "delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %></p>
  <p><%=link_to "Cancel", posts_path %></p>
  <p><%= link_to "Edit Post", edit_post_path(@post)%></p>
<% end %>
</div>

jdgram/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

jdgram/app/views/users/show.html.erb
<% @user.posts.each do |post| %>
  <div class="show-post">
    <p><%= link_to post.user.user_name, user_path(post.user) %></p>
    <div class="post-picture">
      <%= image_tag post.image.url(:medium) %><br>
    </div>
    <div class="post-caption">
      <%= post.caption %>
    </div>
  </div>
<% end %>